//! Block initialization command - scaffolds a new Jig Block project

use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

/// Available block templates
#[derive(Debug, Clone, Copy)]
pub enum Template {
    RustWasi,
    TinyGoWasi,
    TextOnly,
}

impl Template {
    pub fn name(&self) -> &'static str {
        match self {
            Template::RustWasi => "rust-wasi",
            Template::TinyGoWasi => "tinygo-wasi",
            Template::TextOnly => "text-only",
        }
    }

    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "rust-wasi" | "rust" => Some(Template::RustWasi),
            "tinygo-wasi" | "tinygo" | "go" => Some(Template::TinyGoWasi),
            "text-only" | "text" => Some(Template::TextOnly),
            _ => None,
        }
    }
}

/// Initialize a new block project at the specified path
pub fn init_block(
    name: &str,
    template: Template,
    output_dir: Option<&Path>,
    author_did: &str,
) -> Result<PathBuf> {
    // Determine output directory
    let project_dir = if let Some(dir) = output_dir {
        dir.join(name)
    } else {
        PathBuf::from(name)
    };

    // Check if directory already exists
    if project_dir.exists() {
        anyhow::bail!(
            "Directory '{}' already exists. Use a different name or remove the existing directory.",
            project_dir.display()
        );
    }

    // Create project directory
    fs::create_dir_all(&project_dir)
        .with_context(|| format!("Failed to create directory '{}'", project_dir.display()))?;

    println!(
        "Creating new Jig Block: {} (template: {})",
        name,
        template.name()
    );
    println!("  Directory: {}", project_dir.display());

    // Create manifest
    create_manifest(&project_dir, name, author_did, &template)?;

    // Create template-specific files
    match template {
        Template::RustWasi => create_rust_wasi_template(&project_dir, name)?,
        Template::TinyGoWasi => create_tinygo_wasi_template(&project_dir, name)?,
        Template::TextOnly => create_text_only_template(&project_dir, name)?,
    }

    // Create common files
    create_gitignore(&project_dir)?;
    create_readme(&project_dir, name, &template)?;

    println!("\n✓ Block initialized successfully!");
    println!("\nNext steps:");
    println!("  cd {}", name);

    match template {
        Template::RustWasi => {
            println!("  cargo build --target wasm32-wasi --release");
            println!("  jig block lint .");
            println!(
                "  jig block run target/wasm32-wasi/release/{}.wasm",
                name.replace('-', "_")
            );
        }
        Template::TinyGoWasi => {
            println!("  tinygo build -target=wasi -o {}.wasm .", name);
            println!("  jig block lint .");
            println!("  jig block run {}.wasm", name);
        }
        Template::TextOnly => {
            println!("  # Edit block.toml to add your content");
            println!("  jig send --block .");
        }
    }

    Ok(project_dir)
}

/// Create block.toml manifest
fn create_manifest(
    project_dir: &Path,
    name: &str,
    author_did: &str,
    template: &Template,
) -> Result<()> {
    let manifest_path = project_dir.join("block.toml");

    // TODO: Once jig-core provides TOML serialization with comments,
    // use BlockManifest::builder() to create and serialize
    // For now, write a simplified TOML manually with helpful comments
    let toml_content = format!(
        r#"# Jig Block Manifest
# Generated by jig-cli

[block]
name = "{name}"
version = "0.1.0"
description = "A new Jig Block"
template = "{template}"

[author]
did = "{author_did}"

[capabilities]
# Uncomment capabilities as needed:
# network = {{ allowed_domains = ["example.com"] }}
# storage = {{ read_only = true }}
# crypto = {{ operations = ["sign", "verify"] }}

[execution]
# Resource limits (optional - defaults will be applied)
# fuel_max = 5000000
# memory_max_mb = 32
# timeout_ms = 250

[metadata]
# Add custom metadata here
created_at = "{timestamp}"
"#,
        name = name,
        template = template.name(),
        author_did = author_did,
        timestamp = chrono::Utc::now().to_rfc3339()
    );

    fs::write(&manifest_path, toml_content)
        .with_context(|| format!("Failed to write manifest to {}", manifest_path.display()))?;

    println!("  Created: block.toml");
    Ok(())
}

/// Create Rust WASI template files
fn create_rust_wasi_template(project_dir: &Path, name: &str) -> Result<()> {
    // Include template content from embedded files
    let template_content = include_str!("../../templates/rust-wasi/template.rs");
    let cargo_toml = include_str!("../../templates/rust-wasi/Cargo.toml.template");

    // Create src directory
    let src_dir = project_dir.join("src");
    fs::create_dir_all(&src_dir)?;

    // Write main.rs
    fs::write(src_dir.join("lib.rs"), template_content).context("Failed to write lib.rs")?;
    println!("  Created: src/lib.rs");

    // Write Cargo.toml with name substitution
    let cargo_content = cargo_toml.replace("{{name}}", name);
    fs::write(project_dir.join("Cargo.toml"), cargo_content)
        .context("Failed to write Cargo.toml")?;
    println!("  Created: Cargo.toml");

    // Create .cargo/config.toml for wasm32-wasi target
    let cargo_config_dir = project_dir.join(".cargo");
    fs::create_dir_all(&cargo_config_dir)?;
    fs::write(
        cargo_config_dir.join("config.toml"),
        r#"[build]
target = "wasm32-wasi"

[target.wasm32-wasi]
rustflags = ["-C", "opt-level=z", "-C", "lto=yes"]
"#,
    )
    .context("Failed to write .cargo/config.toml")?;
    println!("  Created: .cargo/config.toml");

    Ok(())
}

/// Create TinyGo WASI template files
fn create_tinygo_wasi_template(project_dir: &Path, name: &str) -> Result<()> {
    let template_content = include_str!("../../templates/tinygo-wasi/template.go");

    // Write main.go
    fs::write(project_dir.join("main.go"), template_content).context("Failed to write main.go")?;
    println!("  Created: main.go");

    // Write go.mod
    let go_mod = format!(
        r#"module {name}

go 1.21
"#,
        name = name
    );
    fs::write(project_dir.join("go.mod"), go_mod).context("Failed to write go.mod")?;
    println!("  Created: go.mod");

    Ok(())
}

/// Create text-only template (no WASM)
fn create_text_only_template(_project_dir: &Path, _name: &str) -> Result<()> {
    // For text-only blocks, the manifest is sufficient
    // The content will be in the metadata section
    println!("  (text-only block - edit block.toml to add content)");
    Ok(())
}

/// Create .gitignore
fn create_gitignore(project_dir: &Path) -> Result<()> {
    let gitignore = r#"# Rust
target/
Cargo.lock

# Go
*.wasm
go.sum

# Jig
*.jigb
.jig/

# OS
.DS_Store
Thumbs.db
"#;

    fs::write(project_dir.join(".gitignore"), gitignore).context("Failed to write .gitignore")?;
    println!("  Created: .gitignore");
    Ok(())
}

/// Create README.md
fn create_readme(project_dir: &Path, name: &str, template: &Template) -> Result<()> {
    let readme = format!(
        r#"# {name}

A Jig Block created with the **{template}** template.

## What is this?

This is a Jig Block - an executable, portable unit of code that can run on Jig servers,
in the CLI, or in compatible runtimes.

## Building

{build_instructions}

## Running Locally

```bash
jig block run {run_target} --receipt receipt.json
```

## Deploying

```bash
jig send --block .
```

## Learn More

- [Jig Protocol Docs](https://github.com/jig-protocol/jig)
- [Block Execution Model](https://github.com/jig-protocol/jig/blob/main/repos/jig-spec/src/block-execution.md)
- [Capabilities](https://github.com/jig-protocol/jig/blob/main/repos/jig-spec/src/block-execution.md#capabilities)
"#,
        name = name,
        template = template.name(),
        build_instructions = match template {
            Template::RustWasi =>
                r#"```bash
cargo build --target wasm32-wasi --release
```

The output will be in `target/wasm32-wasi/release/*.wasm`"#,
            Template::TinyGoWasi =>
                r#"```bash
tinygo build -target=wasi -o block.wasm .
```"#,
            Template::TextOnly => "No build step required - this is a text-only block.",
        },
        run_target = match template {
            Template::RustWasi =>
                format!("target/wasm32-wasi/release/{}.wasm", name.replace('-', "_")),
            Template::TinyGoWasi => "block.wasm".to_string(),
            Template::TextOnly => ".".to_string(),
        }
    );

    fs::write(project_dir.join("README.md"), readme).context("Failed to write README.md")?;
    println!("  Created: README.md");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_template_from_name() {
        assert!(matches!(
            Template::from_name("rust"),
            Some(Template::RustWasi)
        ));
        assert!(matches!(
            Template::from_name("rust-wasi"),
            Some(Template::RustWasi)
        ));
        assert!(matches!(
            Template::from_name("tinygo"),
            Some(Template::TinyGoWasi)
        ));
        assert!(matches!(
            Template::from_name("text-only"),
            Some(Template::TextOnly)
        ));
        assert!(Template::from_name("invalid").is_none());
    }

    #[test]
    fn test_init_block_creates_directory() -> Result<()> {
        let temp_dir = TempDir::new()?;
        let project_name = "test-block";

        let project_path = init_block(
            project_name,
            Template::TextOnly,
            Some(temp_dir.path()),
            "did:jig:test:alice",
        )?;

        assert!(project_path.exists());
        assert!(project_path.join("block.toml").exists());
        assert!(project_path.join("README.md").exists());
        assert!(project_path.join(".gitignore").exists());

        Ok(())
    }

    #[test]
    fn test_init_block_fails_if_exists() -> Result<()> {
        let temp_dir = TempDir::new()?;
        let project_name = "test-block";

        // Create first time - should succeed
        init_block(
            project_name,
            Template::TextOnly,
            Some(temp_dir.path()),
            "did:jig:test:alice",
        )?;

        // Try to create again - should fail
        let result = init_block(
            project_name,
            Template::TextOnly,
            Some(temp_dir.path()),
            "did:jig:test:alice",
        );

        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("already exists"));

        Ok(())
    }
}
